routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');
Route::get('send', 'HomeController@sendNotification');
Route::get('/plans', 'PlanController@index')->name('plans.index');
Route::get('/plan/{plan}', 'PlanController@show')->name('plans.show');
Route::post('/subscription', 'SubscriptionController@store')->name('subscription.store');

Route::group(['middleware'=>'visitors'], function(){
    Route::get('/register', 'RegisterController@register');
    Route::post('/register', 'RegisterController@postRegister');
    
    Route::get('/login', 'LoginController@login');
    Route::post('/login', 'LoginController@postLogin');
});



Route::post('/logout', 'LoginController@logout');

//user routes
Route::get('post/{post}','UserPostController@index')->name('post');
Route::get('/user/posts', 'UserPostController@showPosts')->name('posts');
Route::post('/like','UserPostController@likePost')->name('like');
Route::get('user/dashboard','UserController@profileEditing' )->middleware('users');


//admin routes
Route::get('admin/dashboard','AdminController@editing' )->middleware('admin');

Route::resource('admin/user','CreatingUsersController');

//post routes
Route::resource('admin/post', 'PostController');
//Route::get('admin/post/getDatatable','PostController@getDatatable')->name('post.getDatatable');



//tag routes
Route::resource('admin/tag', 'TagController');
//Route::get('admin/tag/get_datatable','TagController@get_datatable')->name('tag.get_datatable');

//category routes
Route::resource('admin/category', 'CategoryController');
//Route::get('admin/category/get_datatable','CategoryController@get_datatable')->name('category.get_datatable');

Route::get('email', 'EmailController@sendEmail');

app/Post.php
<?php

namespace App;

use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function categories()
    {
        return $this->belongsToMany('App\Category','category_post');
    }
    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function user(){
        return $this->belongsTo('App\User');
    }
    
    public function likes(){
        return $this->belongsTo('App\Like');
      }

       //Accessors
    public function getNameAttribute($value){
        return ucwords($value);
    }

      //Mutators
    public function setSlugAttribute($value){
    $this->attributes['slug'] = strtolower($value);
    }
    //global scope
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new ActiveScope);
    }
    //local scope
    public function scopePublished($query)
    {
        return $query->where('publish_date','<',\Carbon\Carbon::now());
    }
    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

use App\Post;
use App\Http\Resources\PostResource;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:api', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('created_at', 'DESC')->paginate(10);
        return PostResource::collection($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'bail|required|min:3',
            'body' => 'required'
        ]);
    
        $post = new Post();
        $post->title = $request->input('title');
        $post->subtitle = $request->input('subtitle');
        $post->body = $request->input('body');
        $now = date('YmdHis');
        $post->slug = str_slug($post->title) . '-' . $now;
        $post->user_id = auth('api')->user()->id;
        
        $post->save();
        return new PostResource($post);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::where('slug',$slug)->firstOrFail();
        return new PostResource($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'bail|required|min:3',
            'body' => 'required'
        ]);
        $post = Post::find($id);
        $post->title = $request->input('title');
        $post->body = $request->input('body');
        $userId = auth('api')->user()->id;
        if ($post->user_id !== $userId ) {
            return response()->json(['error' => 'This is not your post'], 401);
        }
        $post->save();
        return new PostResource($post);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        
        $userId = auth('api')->user()->id;
        if ($post->user_id !== $userId ) {
            return response()->json(['error' => 'This is not your post'], 401);
        }
        $post->delete();
        return response()->json(null, 204);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use App\Post;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Validator;
use URL;
use Yajra\Datatables\Facades\Datatables;
use App\Events\PostCreated;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax())
        {
            return datatables()->of(Post::latest()->get())
                    ->addColumn('action',function($post){
                        $button = '<a type="button" href="'. route('post.edit', $post->id) .'"
                        name="edit" 
                        class="edit btn btn-primary btn-sm">Edit</a>';
                        $button .= '&nbsp;';
                        $button .='<a type="button"
                           name="delete" href="'. route('post.destroy', $post->id) .'"
                           class="delete btn btn-primary btn-sm">Delete</a>';
                        return $button;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        $posts = Post::all();
        return view ('admin.post.show', compact('posts'));
    }
    //public function getdatatable()
    //{
    //    return Datatables::of(Post::get())->make(true);
    //}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.post.post');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|unique:posts|max:255',
            'subtitle'=>'required',
            //'slug' => 'required',
            'body' => 'required',
            'image'=> 'required'
        ]);
        $post = new Post;
        $post->user_id = Sentinel::getUser()->id;
        $post->title = $request->input('title');
        $post->subtitle = $request->input('subtitle');
       // $post->slug = $request->input('slug');
        $post->body = $request->input('body');
        
        if(Input::hasFile('image'))
        {
          $file = Input::file('image');
          $file->move(public_path(). '/posts/',
          $file->getClientOriginalName());
          $url = URL::to("/") . '/posts/' . $file->getClientOriginalName();
        }
        $post->image = $url;
        $post->publish_date=$request->input('publish_date');
        $post->save();

        event(new PostCreated($post));

        return redirect(route('post.index'))->
        with('success','Post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::where('id',$id)->first();
        return view('admin.post.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'title' => 'required|max:255',
            'subtitle'=>'required',
            'slug' => 'required',
            'body' => 'required',
            'image'=> 'required',
            
        ]);
        $post = Post::find($id);
        $post->user_id = Sentinel::getUser()->id;
        $post->title = $request->input('title');
        $post->subtitle = $request->input('subtitle');
        $post->slug = $request->input('slug');
        $post->body = $request->input('body');
        
        if(Input::hasFile('image'))
        {
          $file = Input::file('image');
          $file->move(public_path(). '/posts/',
          $file->getClientOriginalName());
          $url = URL::to("/") . '/posts/' . $file->getClientOriginalName();
        }
        $post->image = $url;
        $post->publish_date=$request->input('publish_date');
        $post->save();

        return redirect(route('post.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::where('id',$id)->delete();
        return redirect()->back();
    }

}

resources/views/admin/post/edit.blade.php
@extends('adminlte::page')

@section('content')  
<html>
  <h3 class="box-title">Edit Post</h3>
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Titles</h3>
    </div>
  <form role="form" action="{{ route('post.update',$post->id) }}" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('PUT') }}
     <div class="box-body">
       <div class="col-lg-6">
       <div class="form-group">
         <label for="title">Post Title</label>
       <input type="text" class="form-control" id="title" name="title" placeholder="Title" value="{{$post->title}}">
       </div>
       @error('title')
    <div class="alert alert-danger">{{ $message }}</div>
     @enderror
       <div class="form-group">
          <label for="subtitle">Post Subtitle</label>
       <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Subtitle" value="{{$post->subtitle}}">
        </div>
        @error('subtitle')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
            <label for="slug">Post Slug</label>
        <input type="text" class="form-control" id="slug" name="slug" placeholder="Slug" value="{{$post->slug}}">
          </div>
        @error('slug')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
       </div>
       <div class="col-lg-6">
        <div class="form-group">
          <label for="image">Image</label>
        <input type="file" name="image" id="image" value="{{$post->image}}">
        </div>
        @error('image')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group"> 
            <label class="control-label" for="publish_date">Publish Date</label>
            <input class="form-control" id="publish_date" name="publish_date" placeholder="YYYY/MM/DD" type="text"/>
          </div>
       <div class="checkbox">
         <label>
           <input type="checkbox" name="status" @if($post->status==1) checked @endif> Publish
         </label>
       </div>
    </div>
  </div>
<script src="{{URL::to('src./js/vendor/tinymce/js/tinymce/tinymce.min.js')}}"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
  <div class="panel-body">
  <textarea class="textarea"  placeholder="Write content here!" id="body" name="body" style="width: 100%" >{{$post->body}}</textarea>
  <br/> @error('body')
  <div class="alert alert-danger">{{ $message }}</div>
@enderror
  </div>

  <div class="box-footer">
      <button type="submit" class="btn btn-primary">Submit </button>
      <a  href='{{route('post.index')}}' class="btn btn-warning">Back</a>
    </div>
  </form>
  </div>
  </html>
  @endsection

resources/views/admin/post/post.blade.php
@extends('adminlte::page')

@section('content')  
<html>
  <h3 class="box-title">Write Post</h3>
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Titles</h3>
    </div>
  <form role="form" action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}
     <div class="box-body">
       <div class="col-lg-6">
       <div class="form-group">
         <label for="title">Post Title</label>
         <input type="text" class="form-control" id="title" name="title" placeholder="Title">
       </div>
       @error('title')
    <div class="alert alert-danger">{{ $message }}</div>
     @enderror
       <div class="form-group">
          <label for="subtitle">Post Subtitle</label>
          <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Subtitle">
        </div>
        @error('subtitle')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
            <label for="slug">Post Slug</label>
            <input type="text" class="form-control" id="slug" name="slug" placeholder="Slug">
          </div>
        @error('slug')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
       </div>
       <div class="col-lg-6">
        <div class="form-group">
          <label for="image">Image</label>
          <input type="file" name="image" id="image">
        </div>
        @error('image')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group"> 
          <label class="control-label" for="publish_date">Publish Date</label>
          <input class="form-control" id="publish_date" name="publish_date" placeholder="YYYY/MM/DD" type="text"/>
        </div>
        <div class="checkbox">
         <label>
           <input type="checkbox" name="status"> Publish
         </label>
       </div>
    </div>
  </div>
<script src="{{URL::to('src./js/vendor/tinymce/js/tinymce/tinymce.min.js')}}"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
  <div class="panel-body">
    <textarea class="textarea"  placeholder="Write content here!" id="body" name="body" style="width: 100%"></textarea>
  <br/> @error('body')
  <div class="alert alert-danger">{{ $message }}</div>
@enderror
  </div>

  <div class="box-footer">
      <button type="submit" class="btn btn-primary">Submit </button>
      <a  href='{{route('post.index')}}' class="btn btn-warning">Back</a>
    </div>
  </form>
  </div>
  </html>
  @endsection

  

resources/views/admin/post/show.blade.php
@extends('adminlte::page')
@section('content_header')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
<a class = 'col-lg-offset-5 btn btn-success'  href="{{ route('post.create')}}"> Add New Post</a>
@stop
@section('content')
<table id="posts"  class="table table-striped table-bordered responsive resourceTable"  style="width: 100%;">
    <thead>
        <tr>
                <th> Id</th>
                <th>User_id</th>
                <th>Title</th>
                <th>Subtitle</th>
                <th>Slug</th>
                <th>Body</th>
                <th>Publish Date </th>
                <th>Status</th>
                <th>Image</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>Action</th>
        </tr>
    </thead>
</table>
@endsection


@section('js')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
        $('#posts').DataTable({
            processing: true,
            serverSide: true,
            autoWidth: true,
            ajax: {
                url: "{{route('post.index')}}",
              },
            columns: [
                {data:'id', name:'id'},
                {data:'user_id', name:'user_id'},
                {data:'title', name:'title'},
                {data:'subtitle', name:'subtitle'},
                {data:'slug', name:'slug'},
                {data:'body', name:'body'},
                {data:'publish_date', name:'publish_date'},
                {data:'status', name:'status'},
                {data:'image', name:'image'},
                {data:'created_at', name:'created_at'},
                {data:'updated_at', name:'updated_at'},
                {data: 'action', name: 'action', orderable: false}
            ]
        });
    });
</script>
@stop