routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');
Route::get('send', 'HomeController@sendNotification');
Route::get('/plans', 'PlanController@index')->name('plans.index');
Route::get('/plan/{plan}', 'PlanController@show')->name('plans.show');
Route::post('/subscription', 'SubscriptionController@store')->name('subscription.store');

Route::group(['middleware'=>'visitors'], function(){
    Route::get('/register', 'RegisterController@register');
    Route::post('/register', 'RegisterController@postRegister');
    
    Route::get('/login', 'LoginController@login');
    Route::post('/login', 'LoginController@postLogin');
});



Route::post('/logout', 'LoginController@logout');

//user routes
Route::get('post/{post}','UserPostController@index')->name('post');
Route::get('/user/posts', 'UserPostController@showPosts')->name('posts');
Route::post('/like','UserPostController@likePost')->name('like');
Route::get('user/dashboard','UserController@profileEditing' )->middleware('users');


//admin routes
Route::get('admin/dashboard','AdminController@editing' )->middleware('admin');

Route::resource('admin/user','CreatingUsersController');

//post routes
Route::resource('admin/post', 'PostController');
//Route::get('admin/post/getDatatable','PostController@getDatatable')->name('post.getDatatable');



//tag routes
Route::resource('admin/tag', 'TagController');
//Route::get('admin/tag/get_datatable','TagController@get_datatable')->name('tag.get_datatable');

//category routes
Route::resource('admin/category', 'CategoryController');
//Route::get('admin/category/get_datatable','CategoryController@get_datatable')->name('category.get_datatable');

Route::get('email', 'EmailController@sendEmail');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = "tags";
    public function posts()
    {
        return $this->belongsToMany('App\Post', 'post_tag');
    }

     //Accessors
     public function getNameAttribute($value){
        return ucwords($value);
    }

      //Mutators
  public function setSlugAttribute($value){
    $this->attributes['slug'] = strtolower($value);
}
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use Yajra\Datatables\Facades\Datatables;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax())
        {
            return datatables()->of(Tag::latest()->get())
                    ->addColumn('action',function($tag){
                        $button = '<a href="'. route('tag.edit', $tag->id) .'" type="button"
                        name="edit" 
                        class="edit btn btn-primary btn-sm">Edit</a>';
                        $button .= '&nbsp;';
                        $button .='<a href="'. route('tag.destroy', $tag->id) .'" type="button"
                           name="delete" 
                           class="delete btn btn-primary btn-sm">Delete</button>';
                        return $button;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view ('admin.tag.show');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.tag');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|unique:tags',
            'slug' => 'required',
        ]);
        $tag = new Tag;
        $tag->name = $request->input('name');
        $tag->slug = $request->input('slug');
        $tag->save();
        return redirect(route('tag.index'))->
        with('response','Tag created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::where('id',$id)->first();
        return view('admin.tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|unique:tags',
            'slug' => 'required',
        ]);
        $tag = Tag::find($id);
        $tag->name = $request->input('name');
        $tag->slug = $request->input('slug');
        $tag->save();
        return redirect(route('tag.index'))->
        with('response','Tag updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::where('id',$id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/tag/edit.blade.php
@extends('adminlte::page')

@section('content')
<html>
        <h3 class="box-title">Edit Tag</h3>
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Tags</h3>
          </div>
        <form role="form" action="{{ route('tag.update',$tag->id) }}"  method="POST">
          {{ csrf_field()}}
          {{ method_field('PUT') }}
           <div class="box-body">
             <div class="col-lg-offset-3 col-lg-6">
             <div class="form-group">
               <label for="name">Tag Title</label>
             <input type="text" class="form-control" id="name" name="name" placeholder="Tag Title" value="{{$tag->name}}">
             </div>
             @error('name')
             <div class="alert alert-danger">{{ $message }}</div>
           @enderror
              <div class="form-group">
                  <label for="slug">Tag Slug</label>
              <input type="text" class="form-control" id="slug" name="slug" placeholder="Slug" value="{{$tag->slug}}">
                </div>
                @error('slug')
                <div class="alert alert-danger">{{ $message }}</div>
              @enderror
                <div class="form-group">
                        <button type="submit" class="btn btn-primary">Submit </button>
                <a  href='{{route('tag.index')}}' class="btn btn-warning">Back</a>
                </div>
             </div>
           </form>
        </div>
    </div> 
  </div>
</html>
@endsection

resources/views/admin/tag/show.blade.php
@extends('adminlte::page')
@section('content_header')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
<a class = 'col-lg-offset-5 btn btn-success'  href="{{ route('tag.create')}}"> Add New Tag</a>
@stop
@section('content')
<table id="tags"  class="table table-striped table-bordered responsive resourceTable">
    <thead>
        <tr>
            <th>Tag Id</th>
            <th>Tag Name</th>
            <th>Tag Slug</th>
            <th> Created_at</th>
            <th>Updated_at</th>
            <th>Action</th>
            
        </tr>
    </thead>
</table>
@endsection


@section('js')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script type="text/javascript">
     $(document).ready(function () {
        $('#tags').DataTable({
            processing: true,
            serverSide: true,
            ajax:{
                url: "{{route('tag.index')}}",
            },
            columns: [
                {data:'id', name:'id'},
                {data:'name', name:'name'},
                {data:'slug', name:'slug'},
                {data:'created_at', name:'created_at'},
                {data:'updated_at', name:'updated_at',},
                {data: 'action', name: 'action', orderable: false}
            ]
        });
    });
</script>
@stop

resources/views/admin/tag/tag.blade.php
@extends('adminlte::page')

@section('content')
<html>
        <h3 class="box-title">Create Tag</h3>
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Tags</h3>
          </div>
        <form role="form" action="{{ route('tag.store') }}"  method="POST">
          {{ csrf_field()}}
           <div class="box-body">
             <div class="col-lg-offset-3 col-lg-6">
             <div class="form-group">
               <label for="name">Tag Title</label>
               <input type="text" class="form-control" id="name" name="name" placeholder="Tag Title">
             </div>
             @error('name')
             <div class="alert alert-danger">{{ $message }}</div>
           @enderror
              <div class="form-group">
                  <label for="slug">Tag Slug</label>
                  <input type="text" class="form-control" id="slug" name="slug" placeholder="Slug">
                </div>
                @error('slug')
                <div class="alert alert-danger">{{ $message }}</div>
              @enderror
                <div class="form-group">
                        <button type="submit" class="btn btn-primary">Submit </button>
                <a  href='{{route('tag.index')}}' class="btn btn-warning">Back</a>
                </div>
             </div>
           </form>
        </div>
    </div> 
  </div>
</html>
@endsection